### ISSUE TITLE
ClassNotFoundException: org.apache.catalina.loader.DevLoader

### ISSUE THREAD

**Issue by pstanton** [tomcatplugin/tomcatplugin#16]
When starting up, my context will not load due to:

Caused by: java.lang.ClassNotFoundException: org.apache.catalina.loader.DevLoader
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:104)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1200)
	... 58 more

If I understand correctly, this class is within your library however obviously is not available to tomcat.

How is DevLoader supposed to be loaded into tomcat prior to my context loading? why isn't this happening?

**Comment by markuskeunecke** [comment]
I think the DevLoader needs to be built and put to your tomcat's classpath manually. The DevLoader is available here for self building.
