### ISSUE TITLE
Unable to open "JVM Settings" in Preferences in Eclipse 2020-09

### ISSUE THREAD

**Issue by shirayuki** [tomcatplugin/tomcatplugin#23]
Unable to open "JVM Settings" in Preferences in Eclipse 2020-09 (4.17.0).
The following error message is displayed:

> Could Not Accept Changes
> The currently displayed page contains invalid values.

**Comment by ConiKost** [comment]
I can confirm with 2020-09 too.

**Comment by shirayuki** [comment]
`org/eclipse/jface/util/Assert.class` was removed from `org.eclipse.jface` in version 3.21.0.

```
java.lang.NoClassDefFoundError: org/eclipse/jface/util/Assert
	at net.sf.eclipse.tomcat.editors.ComboFieldEditor.<init>(ComboFieldEditor.java:53)
	at net.sf.eclipse.tomcat.TomcatJVMPreferencePage.createContents(TomcatJVMPreferencePage.java:83)
	at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:244)
	at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1433)
	at org.eclipse.jface.preference.PreferenceDialog$8.run(PreferenceDialog.java:1196)
	...
Caused by: java.lang.ClassNotFoundException: org.eclipse.jface.util.Assert cannot be found by net.sf.eclipse.tomcat_9.1.4
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 57 more
```

**Comment by ConiKost** [comment]
```org.eclipse.core.runtime.Assert```seems to be the replacement for ```org.eclipse.jface.util.Assert```.

**Comment by matthijslambooy** [comment]
Any workaround for this issue ?

**Comment by shirayuki** [comment]
Here is a workaround:
1. Unzip `org.eclipse.jface_3.20.0.v20200505-1952.jar` (or older version).
1. Find the following class files in `org/eclipse/jface/util/`
`Assert$AssertionFailedException.class`
`Assert.class`
1. Add the above files to `org.eclipse.jface_3.21.0.v20200821-1458.jar` in `plugins` directory.
