### ISSUE TITLE
Unable to install using Eclipse jee-2021-032

### ISSUE THREAD

**Issue by jlvoo** [tomcatplugin/tomcatplugin#34]
Here is the error when I'm using Eclipse jee_2021-032 to install this plug in:

javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:248)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by markuskeunecke** [comment]
@jlvoo Which update site are you using? There was one hosted on sourceforge but is not maintained anymore. A maintained update site can be found at https://devtools.his.de/tomcatplugin/updatesite

The marketplace entry https://marketplace.eclipse.org/content/eclipse-tomcat-plugin also points to the aforementioned site.

**Comment by jlvoo** [comment]
Yes it is using the correct URL.
I'm doing this directly from Eclipse, Help menu -> Eclipse Marketplace -> Search tomcat and Install, then it show this error:

Unable to read repository at https://devtools.his.de/tomcatplugin/updatesite/content.xml.
Received fatal alert: handshake_failure

**Comment by jlvoo** [comment]
I think this may be is my java issue, I'm using OpenJDK 11.0.11. My collegue using OpenJDK 11.0.2, it working fine for her.

**Comment by jochenw** [comment]
I consider it unlikely, that a difference in the VM's patchlevel should make a difference. Instead, I'd suggest to check different proxy settings, different network segments, or the like, as the most likely culprits. However, if it *does* make a difference, I suggest that you compare the contents of the respective cacerts files.

**Comment by markuskeunecke** [comment]
I agree with @jochenw although in some cases the JVM patch level makes a difference, but I just remember something with some old JDK8 versions where in some later builds trust for let's encrypt was added.

I'd also go for @jochenw's approach.

I think it is okay to close this issue for now as it seems to be originated in @jlvoo's environment.
