### ISSUE TITLE
Unable to start tomcat after eclipse 2024-03 update

### ISSUE THREAD

**Issue by nitin-35** [tomcatplugin/tomcatplugin#42]
I recently updated to eclipse version 2024-03 (4.31) and not able to start tomcat using the eclipse tomcat plugin since then.

I get these two errors in the eclipse error log whenever I try to start tomcat.
 
``` 
Impossible to start Tomcat
Check home directory setup in Tomcat preference page/n
```
![image](https://github.com/tomcatplugin/tomcatplugin/assets/49055259/321ec247-3046-4c68-b280-eee86bbfd4ec)

```
java.lang.ClassCastException: class org.eclipse.jdt.internal.core.JavaNature cannot be cast to class org.eclipse.jdt.core.IJavaProject (org.eclipse.jdt.internal.core.JavaNature and org.eclipse.jdt.core.IJavaProject are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @4f68e955)
	at net.sf.eclipse.tomcat.TomcatBootstrap.runTomcatBootstrap(TomcatBootstrap.java:169)
	at net.sf.eclipse.tomcat.TomcatBootstrap.start(TomcatBootstrap.java:112)
	at net.sf.eclipse.tomcat.actions.StartActionDelegate.run(StartActionDelegate.java:43)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:239)
	at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:218)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:581)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:454)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```
![image](https://github.com/tomcatplugin/tomcatplugin/assets/49055259/6f3bcd73-4c48-4462-8f93-5a7c4a098976)

**Comment by matthijslambooy** [comment]
Same here since i updated eclipse to 2024-03 eclipse on Ubuntu

**Comment by The-Arne** [comment]
Yea, I got exactly the same problem.

**Comment by rkurman** [comment]
Same here. I'm wondering, is the necessary change as simple as

```
This was the wrong diff anyway :-) 

```

I have no idea about plug-in development and even less clue about how to test this.

**Comment by rkurman** [comment]
Actually, it was a bit more than that. 

```diff
diff --git a/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/TomcatBootstrap.java b/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/TomcatBootstrap.java
index 27667da..8c7eb93 100644
--- a/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/TomcatBootstrap.java
+++ b/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/TomcatBootstrap.java
@@ -41,6 +41,8 @@ import org.eclipse.jdt.core.IClasspathEntry;
 import org.eclipse.jdt.core.IJavaProject;
 import org.eclipse.jdt.core.JavaCore;
 import org.eclipse.jdt.core.JavaModelException;
+import org.eclipse.jdt.internal.core.JavaNature;
+import org.eclipse.jdt.internal.core.JavaProject;
 import org.eclipse.jdt.launching.JavaRuntime;
 
 import net.sf.eclipse.tomcat.editors.ProjectListElement;
@@ -166,42 +168,46 @@ public abstract class TomcatBootstrap {
 		  if (tomcatProject != null) {
 			  ArrayList webappClasspathFile = new ArrayList();
 			  ArrayList visitedProjects = new ArrayList(); /*IMC*/
-			  IJavaProject javaProject = (IJavaProject) projects[i].getNature(JavaCore.NATURE_ID);
-			  WebClassPathEntries entries = tomcatProject.getWebClassPathEntries();
-
-			  IFile file = null;
-			  if (tomcatProject.getRootDirFolder() == null) {
-				  file = projects[i].getFile(new Path(WEBAPP_CLASSPATH_FILENAME));
-			  } else {
-				  file = tomcatProject.getRootDirFolder().getFile(new Path(WEBAPP_CLASSPATH_FILENAME));
-			  }
-
-			  File cpFile = file.getLocation().makeAbsolute().toFile();
-			  if (cpFile.exists()) {
-				  cpFile.delete();
-			  }
-
-			  if (entries != null) {
-				  getClassPathEntries(javaProject, webappClasspathFile, entries.getList(), visitedProjects);
-
-				  if (tomcatProject.getMavenClasspath()) {
-					  collectMavenDependencies(javaProject, webappClasspathFile, new ArrayList());
+			  
+			  if (projects[i].hasNature(JavaCore.NATURE_ID)) {
+				  IJavaProject javaProject = JavaCore.create(projects[i]);
+			  
+				  WebClassPathEntries entries = tomcatProject.getWebClassPathEntries();
+	
+				  IFile file = null;
+				  if (tomcatProject.getRootDirFolder() == null) {
+					  file = projects[i].getFile(new Path(WEBAPP_CLASSPATH_FILENAME));
+				  } else {
+					  file = tomcatProject.getRootDirFolder().getFile(new Path(WEBAPP_CLASSPATH_FILENAME));
 				  }
-
-				  if (!webappClasspathFile.isEmpty()) {
-
-					  try {
-						  if (cpFile.createNewFile()) {
-							  PrintWriter pw = new PrintWriter(new FileOutputStream(cpFile));
-
-							  for (int j = 0; j < webappClasspathFile.size(); j++) {
-								  //TODO
-								  pw.println(webappClasspathFile.get(j));
+	
+				  File cpFile = file.getLocation().makeAbsolute().toFile();
+				  if (cpFile.exists()) {
+					  cpFile.delete();
+				  }
+	
+				  if (entries != null) {
+					  getClassPathEntries(javaProject, webappClasspathFile, entries.getList(), visitedProjects);
+	
+					  if (tomcatProject.getMavenClasspath()) {
+						  collectMavenDependencies(javaProject, webappClasspathFile, new ArrayList());
+					  }
+	
+					  if (!webappClasspathFile.isEmpty()) {
+	
+						  try {
+							  if (cpFile.createNewFile()) {
+								  PrintWriter pw = new PrintWriter(new FileOutputStream(cpFile));
+	
+								  for (int j = 0; j < webappClasspathFile.size(); j++) {
+									  //TODO
+									  pw.println(webappClasspathFile.get(j));
+								  }
+								  pw.close();
 							  }
-							  pw.close();
+						  } catch (IOException e) {
+							  e.printStackTrace();
 						  }
-					  } catch (IOException e) {
-						  e.printStackTrace();
 					  }
 				  }
 			  }
diff --git a/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/TomcatLauncherPlugin.java b/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/TomcatLauncherPlugin.java
index 19a6eb1..3b31d42 100644
--- a/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/TomcatLauncherPlugin.java
+++ b/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/TomcatLauncherPlugin.java
@@ -424,7 +424,7 @@ public class TomcatLauncherPlugin extends AbstractUIPlugin {
             IProject project = allProject;
             try {
                 if((project.isOpen()) && project.hasNature(JavaCore.NATURE_ID)) {
-                    IJavaProject javaProject = (IJavaProject) project.getNature(JavaCore.NATURE_ID);
+                	IJavaProject javaProject = JavaCore.create(project);
                     if(!alreadyAdded.contains(project))
                     {
                         tempList.add(new ProjectListElement(javaProject.getProject()));
diff --git a/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/VMLauncherUtility.java b/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/VMLauncherUtility.java
index 4551704..e5677e8 100644
--- a/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/VMLauncherUtility.java
+++ b/net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/VMLauncherUtility.java
@@ -238,7 +238,8 @@ public class VMLauncherUtility {
 			IProject project = ((ProjectListElement) iter.next()).getProject();
 			traceBuffer.append("Project " + project.getName());
 			if ((project.isOpen()) && project.hasNature(JavaCore.NATURE_ID)) {
-				tempList.add(project.getNature(JavaCore.NATURE_ID));
+            	IJavaProject javaProject = JavaCore.create(project);
+				tempList.add(javaProject);
 				traceBuffer.append(" added to tempList\n");
 			}
 		}

```

This works with Eclipse 2024-03, but I have not tested this with previous versions.

**Comment by tillneum** [comment]
Hi rkurman, it seems to me that the second diff just reverts the first one.

**Comment by rkurman** [comment]
> Hi rkurman, it seems to me that the second diff just reverts the first one.

Yes, I have literally no control over my Copy/Paste abilities. :-) The comment should be ok now.

**Comment by tillneum** [comment]
Now the diff in https://github.com/tomcatplugin/tomcatplugin/issues/42#issuecomment-2006173368 is what you had before in https://github.com/tomcatplugin/tomcatplugin/issues/42#issuecomment-2004936045

**Comment by rkurman** [comment]
> Now the diff in [#42 (comment)](https://github.com/tomcatplugin/tomcatplugin/issues/42#issuecomment-2006173368) is what you had before in [#42 (comment)](https://github.com/tomcatplugin/tomcatplugin/issues/42#issuecomment-2004936045)

Yes, but it is the correct one. Apologies for the confusion.

**Comment by tillneum** [comment]
So far I managed to confirm that the patch works for both Eclipse 2024-03 and 2023-06.

But it works for me as well if I only apply the patch of class VMLauncherUtility. 

@rkurman Could you test that, too?

**Comment by rkurman** [comment]
@tillneum When only patching `VMLauncherUtility`, I still get exceptions at the other two places `TomcatBootstrap` and `TomcatLauncherPlugin`. So, I am not sure why it would behave differently, but my setup definitely needs the full patch.

**Comment by tillneum** [comment]
Thank you.

**Comment by markuskeunecke** [comment]
@rkurman If the patch provided by you works you could open a pull request to be merged in here. @tillneum: Are you capable of building a release?

**Comment by tillneum** [comment]
There is no need to open a merge request, because I have the patch in my dev workspace. And yes, I'll build a new release soon.

**Comment by markuskeunecke** [comment]
Fine :) @tillneum

**Comment by tillneum** [comment]
Release 9.1.7 is published.

**Comment by matthijslambooy** [comment]
Thanks for the fix!!

**Comment by rkurman** [comment]
Awesome, thank you! Do you know how long it will take until it will be available in the Eclipse Marketplace?

**Comment by markuskeunecke** [comment]
I just updated the listing in the Marketplace.

**Comment by rkurman** [comment]
Sorry for my ignorance, but the Marketplace still offers version 9.1.4. Is there a way to refresh some cache, or does it take some time to become active?

**Comment by The-Arne** [comment]
Might be a cache problem in the market place. For me the eclipse update worked. So even if the market place installs an older version, the update sites seem to deliver the current version.

**Comment by jochenw** [comment]
Marketplace is showing version 9.1.7 now.
