### ISSUE TITLE
Project properties cannot be configured on Eclipse 4.31

### ISSUE THREAD

**Issue by jochenw** [tomcatplugin/tomcatplugin#45]
Hi,

I am getting this picture, when I try to convert a new project to a Tomcat project. Which makes the plugin essentially useless for me.

Thanks,

Jochen

![image](https://github.com/tomcatplugin/tomcatplugin/assets/1055257/c59a03d6-f5bc-45d5-aea5-b1c06a5317e2)

**Comment by markuskeunecke** [comment]
Anything to see in the workspace log located in workspace metadata?

**Comment by jochenw** [comment]
java.lang.ClassCastException: class org.eclipse.jdt.internal.core.JavaNature cannot be cast to class org.eclipse.jdt.core.IJavaProject (org.eclipse.jdt.internal.core.JavaNature and org.eclipse.jdt.core.IJavaProject are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @17949298)
	at net.sf.eclipse.tomcat.TomcatProjectPropertyPage.getJavaProject(TomcatProjectPropertyPage.java:107)
	at net.sf.eclipse.tomcat.TomcatProjectGeneralPropertyPage.createIsTomcatProjectGroup(TomcatProjectGeneralPropertyPage.java:84)
	at net.sf.eclipse.tomcat.TomcatProjectGeneralPropertyPage.createContents(TomcatProjectGeneralPropertyPage.java:60)
	at net.sf.eclipse.tomcat.TomcatProjectPropertyPage.createContents(TomcatProjectPropertyPage.java:62)
	at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:244)
	at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1433)
	at org.eclipse.jface.preference.PreferenceDialog$8.run(PreferenceDialog.java:1196)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1188)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:618)
	at org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:660)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:657)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:820)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:817)
	at org.eclipse.jface.viewers.ColumnViewer.firePostSelectionChanged(ColumnViewer.java:1065)
	at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1185)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:283)
	at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:437)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:154)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:581)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:415)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)

**Comment by jochenw** [comment]
Forgot to mention: I am on 9.1.7.

**Comment by Felix-daoyu** [comment]
Me too !

**Comment by KHELIZ** [comment]
Hi, 
I have the same problem with Tomcat Plugin 1.7 in IDE Eclipse Version: 2024-03 (4.31.0) Build ID: 20240307-1437. 

Thank you in advance for your responsiveness

**Comment by jochenw** [comment]
@markuskeunecke The label "help wanted" is present, but how can we help?

**Comment by markuskeunecke** [comment]
Sorry for not being clear @jochenw. :) Any help in analyzing this or providing a pull request for this is really appreciated. I currently do not have the time to have a deeper look into it.

**Comment by jochenw** [comment]
@markuskeunecke Any chance on a README, or something the like, on how to setup a development environment? (Starting with a clean workspace, and up to the point where, and how, to launch a development version.)
I tried to simply import the project into my workspace, but cannot even make the Compiler happy, due to trouble with the DevLoader.

**Comment by markuskeunecke** [comment]
@jochenw Finally I found some time adding my steps on setting up a development environment and creating a run configuration. As I usually did not work on the DevLoader I currently have no better advice on closing the project to make the compiler errors invisible. As far as I can see the DevLoader is not relevant for this issue.

**Comment by KHELIZ** [comment]
did you resolve the bug?

**Comment by GeorgNepp** [comment]
my fix in "net.sf.eclipse.tomcat/src/net/sf/eclipse/tomcat/TomcatProjectPropertyPage.java":

	protected IJavaProject getJavaProject() throws CoreException {
		IProject       project       = (this.getElement().getAdapter(IProject.class));
		IProjectNature projectNature = project.getNature(JavaCore.NATURE_ID);
		if (projectNature instanceof IJavaProject) {
			return (IJavaProject) projectNature; // legacy implementation
		}
		return JavaCore.create(project); // new implementation; needed since Eclipse 4.31
	}

**Comment by jochenw** [comment]
@markuskeunecke Could, we, please, have a release with the patch from #50 included? Thanks, very much!

**Comment by markuskeunecke** [comment]
@jochenw: Do you mean maybe #51? If yes, maybe @tillneum or @nhnb can help with that as they have access to the hosted update site. I can update the marketplace afterwards.

**Comment by jochenw** [comment]
You are right, @markuskeunecke: Indeed, #51 contains the patch, that I was referring to. Would love to give it a try, because the current issue really bothers me, for quite some time.

**Comment by jochenw** [comment]
@markuskeunecke Any chance, that you could finish the review of #51, and push out a release, please?

**Comment by markuskeunecke** [comment]
@nhnb Can you help out pushing out a new release on https://devtools.his.de/tomcatplugin/updatesite? I will bump up version numbers in preparation.

**Comment by jochenw** [comment]
I'd be happy to help, Markus. Problem is, I have zero experience with Eclipse plugins, apart from installing them. What I attempted, was to to export the subproject net.sf.eclipse.tomcat.feature, but that just produced a bunch of error messages.

**Comment by jochenw** [comment]
@markuskeunecke @nhnb @tillneum 
This issue is now more than one year old. The problem has affected multiple users, and a fix has been committed more than five months ago. So, could we please have an updated version now?

**Comment by markuskeunecke** [comment]
@jochenw: Thanks for reminding us to finally release the plugin. I just have updated the marketplace entry with the new version 9.1.8.
